naam = input("Geef je naam: ")
leeftijd = input("Wat is je leeftijd: ")
gedrag = input("Wat is je gedrag: ")
cadeau1 = input("Wat is je eerste cadeau: ")
cadeau2 = input("Wat is je tweede cadeau: ")
cadeau3 = input("Wat is je derde cadeau: ")
cadeau4 = input("Wat is je vierde cadeau: ")
cadeau5 = input("Wat is je vijfde cadeau: ")

print("Lieve Sint")
print("Ik ben " + naam + " en ik ben " + leeftijd +  " jaar oud.")
print("Ik ben " + gedrag + " geweest dit jaar.")
print ("Graag zou ik " +  cadeau1 + ", " + cadeau2 + ", " + cadeau3 + ", " + cadeau4 + " en " +   cadeau5 + " in mijn schoentje krijgen.")
print("Veel liefs")
print(naam)
